const quotes = [
  "Believe in yourself and keep moving forward.",
  "Success comes from hard work and patience.",
  "Every day is a new chance to learn.",
  "Small steps lead to big achievements.",
  "Never stop learning new things.",
  "Mistakes help us grow and improve.",
  "Stay focused on your goals.",
  "Dream big and work for it.",
  "Practice makes you better every day.",
  "Hard work always pays off.",
  "Be positive and stay strong.",
  "Learning is the key to success.",
  "Do your best in everything you do.",
  "Failure is a step toward success.",
  "Stay calm and keep trying.",
  "Confidence comes from practice.",
  "Never give up on your dreams.",
  "Believe in the power of effort.",
  "Each day brings new opportunities.",
  "Success starts with self-belief.",
  "Be patient and trust the process.",
  "Great things take time.",
  "Work hard and stay humble.",
  "Learning makes life better.",
  "Stay motivated and focused.",
  "Your effort matters every day.",
  "Success is built one day at a time.",
  "Keep improving yourself.",
  "Challenges make you stronger.",
  "Stay consistent in your work.",
  "Believe that you can succeed.",
  "Learning from mistakes is important.",
  "Do not fear failure.",
  "Your future depends on today.",
  "Stay curious and keep learning.",
  "Success requires dedication.",
  "Make progress every day.",
  "Strong habits create success.",
  "Never stop believing in yourself.",
  "Focus on growth, not perfection.",
  "Success begins with action.",
  "Keep learning and keep growing.",
  "Every effort counts.",
  "Stay disciplined and patient.",
  "Hard work builds confidence.",
  "Believe in your journey.",
  "Learning is a lifelong process.",
  "Stay determined and positive.",
  "Success comes to those who try.",
];

const buttons = document.querySelector("button");
const quote = document.querySelector("h1");

buttons.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * 20);
  quote.innerHTML = quotes[randomIndex];
});
